from django.urls import path
from .views import (
    AssociationView, AssociationVerifyView, AssociationLookupView, AssociationRoleView, AssociationListView,
    AdminAssociationView, AdminStatsView, ApartmentView, ApartmentOwnerView, OwnerView,
    CategoryView, CategoryListView,
    AccountingKeyListView, AccountingKeyView,
    BankAccountView, TransactionView,
    ImportPreviewView, ImportConfirmView, ImportDetectView, ImportRecategoriseView,
    CategoryRuleView,
    BudgetView, BudgetItemView, BudgetWizardView, CollectionView,
    CollectionGenerateView, CollectionMatchView, CollectionUnmatchView, CollectionCandidatesView,
    ApartmentImportSourcesView, ApartmentImportPreviewView, ApartmentImportConfirmView,
    ReportView, AnnualStatementView,
)
from .banks.views import (
    BankStatusView,
    BankDisconnectView, AdminBankSyncView, AdminBankHealthView,
)

urlpatterns = [
    path("Apartment/import/sources", ApartmentImportSourcesView.as_view(), name="apartment-import-sources"),
    path("Apartment/import/preview", ApartmentImportPreviewView.as_view(), name="apartment-import-preview"),
    path("Apartment/import/confirm", ApartmentImportConfirmView.as_view(), name="apartment-import-confirm"),
    path("Association/verify", AssociationVerifyView.as_view(), name="association-verify"),
    path("Association/lookup", AssociationLookupView.as_view(), name="association-lookup"),
    path("Association/list/<int:user_id>", AssociationListView.as_view(), name="association-list"),
    path("Association/<int:user_id>", AssociationView.as_view(), name="association-detail"),
    path("Association", AssociationView.as_view(), name="association-create"),
    path("Association/roles/<int:user_id>", AssociationRoleView.as_view(), name="association-roles"),
    path("admin/Association", AdminAssociationView.as_view(), name="admin-association"),
    path("admin/stats", AdminStatsView.as_view(), name="admin-stats"),
    path("Apartment/<int:user_id>", ApartmentView.as_view(), name="apartment-list"),
    path("Apartment", ApartmentView.as_view(), name="apartment-create"),
    path("Apartment/update/<int:apartment_id>", ApartmentView.as_view(), name="apartment-update"),
    path("Apartment/delete/<int:apartment_id>", ApartmentView.as_view(), name="apartment-delete"),
    path("Apartment/enable/<int:apartment_id>", ApartmentView.as_view(), name="apartment-enable"),
    path("Apartment/<int:apartment_id>/owner/<int:owner_id>", ApartmentOwnerView.as_view(), name="apartment-owner-delete"),
    path("Apartment/<int:apartment_id>/owner", ApartmentOwnerView.as_view(), name="apartment-owner-create"),
    path("Owner/<int:user_id>", OwnerView.as_view(), name="owner-list"),
    path("Owner", OwnerView.as_view(), name="owner-create"),
    path("Owner/update/<int:ownership_id>", OwnerView.as_view(), name="owner-update"),
    path("Owner/delete/<int:ownership_id>", OwnerView.as_view(), name="owner-delete"),
    path("Owner/enable/<int:ownership_id>", OwnerView.as_view(), name="owner-enable"),
    path("Category/list", CategoryListView.as_view(), name="category-list-global"),
    path("Category/<int:user_id>", CategoryView.as_view(), name="category-list"),
    path("Category", CategoryView.as_view(), name="category-create"),
    path("Category/update/<int:category_id>", CategoryView.as_view(), name="category-update"),
    path("Category/delete/<int:category_id>", CategoryView.as_view(), name="category-delete"),
    path("Category/enable/<int:category_id>", CategoryView.as_view(), name="category-enable"),
    path("AccountingKey/list", AccountingKeyListView.as_view(), name="accountingkey-list"),
    path("AccountingKey/update/<int:key_id>", AccountingKeyView.as_view(), name="accountingkey-update"),
    path("AccountingKey/delete/<int:key_id>", AccountingKeyView.as_view(), name="accountingkey-delete"),
    path("AccountingKey/enable/<int:key_id>", AccountingKeyView.as_view(), name="accountingkey-enable"),
    path("AccountingKey/<int:user_id>", AccountingKeyView.as_view(), name="accountingkey-admin-list"),
    path("AccountingKey", AccountingKeyView.as_view(), name="accountingkey-create"),
    path("BankAccount/update/<int:bank_account_id>", BankAccountView.as_view(), name="bankaccount-update"),
    path("BankAccount/delete/<int:bank_account_id>", BankAccountView.as_view(), name="bankaccount-delete"),
    path("BankAccount/<int:user_id>", BankAccountView.as_view(), name="bankaccount-list"),
    path("BankAccount", BankAccountView.as_view(), name="bankaccount-create"),
    path("Transaction/categorise/<int:transaction_id>", TransactionView.as_view(), name="transaction-categorise"),
    path("Transaction/<int:user_id>", TransactionView.as_view(), name="transaction-list"),
    path("Transaction", TransactionView.as_view(), name="transaction-create"),
    path("Import/detect", ImportDetectView.as_view(), name="import-detect"),
    path("Import/recategorise", ImportRecategoriseView.as_view(), name="import-recategorise"),
    path("Import/preview", ImportPreviewView.as_view(), name="import-preview"),
    path("Import/confirm", ImportConfirmView.as_view(), name="import-confirm"),
    path("CategoryRule/update/<int:rule_id>", CategoryRuleView.as_view(), name="categoryrule-update"),
    path("CategoryRule/delete/<int:rule_id>", CategoryRuleView.as_view(), name="categoryrule-delete"),
    path("CategoryRule/<int:user_id>", CategoryRuleView.as_view(), name="categoryrule-list"),
    path("CategoryRule", CategoryRuleView.as_view(), name="categoryrule-create"),
    path("Budget/wizard", BudgetWizardView.as_view(), name="budget-wizard"),
    path("Budget/<int:user_id>", BudgetView.as_view(), name="budget-get"),
    path("BudgetItem/update/<int:item_id>", BudgetItemView.as_view(), name="budgetitem-update"),
    path("Collection/generate", CollectionGenerateView.as_view(), name="collection-generate"),
    path("Collection/match", CollectionMatchView.as_view(), name="collection-match"),
    path("Collection/unmatch", CollectionUnmatchView.as_view(), name="collection-unmatch"),
    path("Collection/candidates/<int:collection_id>", CollectionCandidatesView.as_view(), name="collection-candidates"),
    path("Collection/<int:user_id>", CollectionView.as_view(), name="collection-list"),
    path("Report/<int:user_id>", ReportView.as_view(), name="report"),
    path("AnnualStatement/<int:user_id>", AnnualStatementView.as_view(), name="annual-statement"),
    # Bank integration
    path("associations/<int:association_id>/bank/status", BankStatusView.as_view(), name="bank-status"),
    path("associations/<int:association_id>/bank/disconnect", BankDisconnectView.as_view(), name="bank-disconnect"),
    path("admin/associations/<int:association_id>/bank/sync", AdminBankSyncView.as_view(), name="admin-bank-sync"),
    path("admin/bank/health", AdminBankHealthView.as_view(), name="admin-bank-health"),
]
