from django.urls import path
from .views import AssociationView, AssociationLookupView, AssociationRoleView, AssociationListView, AdminAssociationView, ApartmentView, ApartmentOwnerView, OwnerView, CategoryView, BudgetView, BudgetItemView, CollectionView

urlpatterns = [
    path("Association/lookup", AssociationLookupView.as_view(), name="association-lookup"),
    path("Association/list/<int:user_id>", AssociationListView.as_view(), name="association-list"),
    path("Association/<int:user_id>", AssociationView.as_view(), name="association-detail"),
    path("Association", AssociationView.as_view(), name="association-create"),
    path("Association/roles/<int:user_id>", AssociationRoleView.as_view(), name="association-roles"),
    path("admin/Association", AdminAssociationView.as_view(), name="admin-association"),
    path("Apartment/<int:user_id>", ApartmentView.as_view(), name="apartment-list"),
    path("Apartment", ApartmentView.as_view(), name="apartment-create"),
    path("Apartment/update/<int:apartment_id>", ApartmentView.as_view(), name="apartment-update"),
    path("Apartment/delete/<int:apartment_id>", ApartmentView.as_view(), name="apartment-delete"),
    path("Apartment/enable/<int:apartment_id>", ApartmentView.as_view(), name="apartment-enable"),
    path("Apartment/<int:apartment_id>/owner/<int:owner_id>", ApartmentOwnerView.as_view(), name="apartment-owner-delete"),
    path("Apartment/<int:apartment_id>/owner", ApartmentOwnerView.as_view(), name="apartment-owner-create"),
    path("Owner/<int:user_id>", OwnerView.as_view(), name="owner-list"),
    path("Owner", OwnerView.as_view(), name="owner-create"),
    path("Owner/update/<int:ownership_id>", OwnerView.as_view(), name="owner-update"),
    path("Owner/delete/<int:ownership_id>", OwnerView.as_view(), name="owner-delete"),
    path("Owner/enable/<int:ownership_id>", OwnerView.as_view(), name="owner-enable"),
    path("Category/<int:user_id>", CategoryView.as_view(), name="category-list"),
    path("Category", CategoryView.as_view(), name="category-create"),
    path("Category/update/<int:category_id>", CategoryView.as_view(), name="category-update"),
    path("Category/delete/<int:category_id>", CategoryView.as_view(), name="category-delete"),
    path("Category/enable/<int:category_id>", CategoryView.as_view(), name="category-enable"),
    path("Budget/<int:user_id>", BudgetView.as_view(), name="budget-get"),
    path("Budget", BudgetView.as_view(), name="budget-create"),
    path("BudgetItem/update/<int:item_id>", BudgetItemView.as_view(), name="budgetitem-update"),
    path("Collection/<int:user_id>", CollectionView.as_view(), name="collection-list"),
]
