# Generated by Django 4.1.13 on 2026-03-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kennitala', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Finance', 'Finance'), ('User', 'User')], default='User', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('house_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='associations.houseassociation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_entries', to='users.user')),
            ],
            options={
                'db_table': 'users_useraccess',
                'unique_together': {('user', 'house_association')},
            },
        ),
    ]
