# Generated by Django 4.1.13 on 2026-05-04 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_termsacceptance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("chair_changed", "Chair changed"),
                            ("cfo_changed", "CFO changed"),
                            ("association_new", "Association created"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "users_auditlog",
                "ordering": ["-created_at"],
            },
        ),
    ]
