# Generated by Django 4.1.13 on 2026-03-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kennitala', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'db_table': 'associations_houseassociation',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(max_length=50)),
                ('percentage_owned', models.FloatField()),
                ('pay_common_fees', models.BooleanField(default=True)),
                ('building_name', models.CharField(blank=True, default='', max_length=255)),
                ('house_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='associations.houseassociation')),
            ],
            options={
                'db_table': 'associations_apartment',
            },
        ),
    ]
