# Generated by Django 4.1.13 on 2026-03-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'associations_association',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='associations.association')),
            ],
            options={
                'db_table': 'associations_budget',
                'unique_together': {('association', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equally_divided', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='associations.budget')),
            ],
            options={
                'db_table': 'associations_budgetitem',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnr', models.CharField(max_length=8)),
                ('anr', models.CharField(max_length=7)),
                ('size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='associations.association')),
            ],
            options={
                'db_table': 'associations_apartment',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('amount_shared', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_equal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='associations.apartment')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='associations.budget')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='users.user')),
            ],
            options={
                'db_table': 'associations_collection',
                'unique_together': {('budget', 'apartment', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AssociationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHAIR', 'Chair'), ('CFO', 'CFO'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_entries', to='associations.association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_access', to='users.user')),
            ],
            options={
                'db_table': 'associations_associationaccess',
                'unique_together': {('user', 'association')},
            },
        ),
        migrations.CreateModel(
            name='ApartmentOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_payer', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='associations.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='users.user')),
            ],
            options={
                'db_table': 'associations_apartmentownership',
                'unique_together': {('user', 'apartment')},
            },
        ),
    ]
