# Generated by Django 4.1.13 on 2026-03-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='size',
        ),
        migrations.AddField(
            model_name='apartment',
            name='share_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='apartment',
            name='share_eq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
