# Generated by Django 4.1.13 on 2026-03-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0002_remove_apartment_size_apartment_share_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='share_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
