# Generated by Django 4.1.13 on 2026-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0003_apartment_share_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
