# Generated by Django 4.1.13 on 2026-03-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0004_apartment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentownership',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
