# Generated by Django 4.1.13 on 2026-03-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0005_apartmentownership_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SHARED', 'Sameiginlegt'), ('SHARE2', 'Sameign'), ('SHARE3', 'Lóð'), ('EQUAL', 'Jafnskipt')], max_length=20)),
                ('deleted', models.BooleanField(default=False)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='associations.association')),
            ],
            options={
                'db_table': 'associations_category',
            },
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='associations.category'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('budget', 'category')},
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='equally_divided',
        ),
    ]
