# Generated by Django 4.1.13 on 2026-03-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0007_alter_budget_unique_together_budget_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
