# Generated by Django 4.1.13 on 2026-03-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0008_apartment_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMSImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('last_imported_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hms_sources', to='associations.association')),
            ],
            options={
                'db_table': 'associations_hmsimportsource',
                'unique_together': {('association', 'url')},
            },
        ),
    ]
