# Generated by Django 4.1.13 on 2026-03-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0009_add_hmsimportsource'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('association', 'fnr')},
        ),
    ]
