# Generated by Django 4.1.13 on 2026-03-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0013_accountingkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories', to='associations.accountingkey'),
        ),
        migrations.AddField(
            model_name='category',
            name='income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_categories', to='associations.accountingkey'),
        ),
    ]
