# Generated by Django 4.1.13 on 2026-03-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0014_category_accounting_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('asset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='associations.accountingkey')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='associations.association')),
            ],
            options={
                'db_table': 'associations_bankaccount',
            },
        ),
    ]
