# Generated by Django 4.1.13 on 2026-03-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0015_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('IMPORTED', 'Innflutt'), ('CATEGORISED', 'Flokkað'), ('RECONCILED', 'Jafnað')], default='IMPORTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='associations.bankaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='associations.category')),
            ],
            options={
                'db_table': 'associations_transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
