# Generated by Django 4.1.13 on 2026-03-31 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0017_categoryrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='paid_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_payment', to='associations.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer_kennitala',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
