# Generated by Django 4.1.13 on 2026-04-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_superadmin'),
        ('associations', '0019_association_registry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Handvirkt'), ('BANK_SYNC', 'Bankajöfnun')], default='MANUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('SHARED', 'Sameiginlegt'), ('SHARE2', 'Hiti'), ('SHARE3', 'Lóð'), ('EQUAL', 'Jafnskipt'), ('INCOME', 'Tekjur')], max_length=20),
        ),
        migrations.CreateModel(
            name='BankNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CONSENT_EXPIRY', 'Samþykki rennur út')], max_length=30)),
                ('recipients', models.JSONField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_notification_logs', to='associations.association')),
            ],
            options={
                'db_table': 'associations_banknotificationlog',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BankConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('LANDSBANKINN', 'Landsbankinn'), ('ARION', 'Arion'), ('ISLANDSBANKI', 'Íslandsbanki')], max_length=20)),
                ('consent_id', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField()),
                ('consent_expires_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('renewal_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_consent', to='associations.association')),
            ],
            options={
                'db_table': 'associations_bankconsent',
            },
        ),
        migrations.CreateModel(
            name='BankApiAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('LANDSBANKINN', 'Landsbankinn'), ('ARION', 'Arion'), ('ISLANDSBANKI', 'Íslandsbanki')], max_length=20)),
                ('endpoint', models.CharField(max_length=500)),
                ('http_method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_audit_logs', to='associations.association')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_audit_logs', to='users.user')),
            ],
            options={
                'db_table': 'associations_bankapiauditlog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
