# Generated by Django 4.1.13 on 2026-04-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0020_bank_consent_and_transaction_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTokenCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=32)),
                ("access_token", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "associations_banktokencache",
            },
        ),
        migrations.CreateModel(
            name="BankClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_id", models.CharField(max_length=64)),
                ("payor_national_id", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Ógreitt"),
                            ("PAID", "Greitt"),
                            ("CANCELLED", "Afturkallað"),
                        ],
                        default="UNPAID",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField()),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_claim",
                        to="associations.collection",
                    ),
                ),
            ],
            options={
                "db_table": "associations_bankclaim",
            },
        ),
        migrations.CreateModel(
            name="AssociationBankSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_id", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "association",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_settings",
                        to="associations.association",
                    ),
                ),
            ],
            options={
                "db_table": "associations_associationbanksettings",
            },
        ),
    ]
