# Generated by Django 4.1.13 on 2026-04-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0021_add_bank_customer_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankapiauditlog",
            name="bank",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="BankConsent",
        ),
    ]
