# Generated by Django 4.1.13 on 2026-04-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_last_login_to_user'),
        ('associations', '0022_drop_bankconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assoc_ssn', models.CharField(max_length=10)),
                ('assoc_name', models.CharField(max_length=255)),
                ('chair_ssn', models.CharField(max_length=10)),
                ('chair_name', models.CharField(max_length=255)),
                ('chair_email', models.EmailField(max_length=254)),
                ('chair_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='users.user')),
            ],
            options={
                'db_table': 'associations_registrationrequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
