# Generated by Django 4.1.13 on 2026-04-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0023_add_registration_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=16),
        ),
    ]
