# Generated by Django 4.1.13 on 2026-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0027_transfer_detection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaccounttransfer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
