# Generated by Django 4.1.13 on 2026-05-01 12:30

from django.db import migrations, models


def backfill_transfer_status(apps, schema_editor):
    Transaction = apps.get_model("associations", "Transaction")
    InterAccountTransfer = apps.get_model("associations", "InterAccountTransfer")
    transfer_tx_ids = set(
        InterAccountTransfer.objects.values_list("inbound_transaction_id", flat=True)
    ) | set(
        InterAccountTransfer.objects.values_list("outbound_transaction_id", flat=True)
    )
    Transaction.objects.filter(id__in=transfer_tx_ids, status="RECONCILED").update(status="TRANSFER")


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0028_alter_interaccounttransfer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("IMPORTED", "Innflutt"),
                    ("CATEGORISED", "Flokkað"),
                    ("RECONCILED", "Jafnað"),
                    ("TRANSFER", "Millifærsla"),
                    ("PENDING_TRANSFER", "Bíður millifærslu"),
                ],
                default="IMPORTED",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_transfer_status, migrations.RunPython.noop),
    ]
