# Generated by Django 4.1.13 on 2026-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0029_transfer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="fnr",
            field=models.CharField(max_length=12),
        ),
    ]
