# Generated by Django 4.1.13 on 2026-05-17 14:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0032_bankaccount_connected_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="opening_balance_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
