# Generated by Django 4.1.13 on 2026-07-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0039_alter_banktokencache_association"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationbanksettings",
            name="isb_claim_account",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="associationbanksettings",
            name="isb_password",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="associationbanksettings",
            name="isb_username",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
